Add Ferry Chandra
Daskom-Lab/2021-Academy pull request #9
Opened 2021-08-05 07:53 UTC by ferry5245

Add Ferry Chandra, sebagai mentee

2021-08-05 08:20 UTC, fakhrip requested changes

2021-08-05 08:20 UTC, fakhrip commented on README.md
>  # Contents
Ini baris di antara kedua hal ini harus ada baris kosong ya, jangan dihapus baris kosong nya, coba di ubah ya fer

2021-08-05 08:20 UTC, fakhrip commented on README.md
>  # Contents
@ferry5245

2021-08-05 08:21 UTC, fakhrip commented on README.md
>  # Contents
```suggestion
- [Ferry Chandra](https://github.com/ferry5245) [FEY]
  > Sebagai mentee
  
# Contents
```
Harusnya begitu

2021-08-05 08:21 UTC, fakhrip commented on README.md
>  # Contents
Nanti setelah commit begitu, kan commit nya jadi ada 2 kali tuh, kamu squash dulu commitnya, buat caranya coba tanya ke rusma yang tadi juga ngelakuin hal yang sama

2021-08-05 08:22 UTC, fakhrip commented on README.md
>  # Contents
https://www.youtube.com/watch?v=V5KrD7CmO4o atau ini buat referensinya

2021-08-05 09:06 UTC, IritaSee requested changes

2021-08-05 09:06 UTC, IritaSee commented on README.md
>  # Contents
Sama sih kalo dari saya, dan saran juga untuk melakukan perubahannya di fork hasil kalian dulu, dan lebih baik lagi di local ya biar gak bingung sendiri

2021-08-06 06:28 UTC, IritaSee commented
Jangan lupa di commit kalo ada perubahan... ;)

2021-08-06 08:40 UTC, fakhrip approved these changes
Sipp mantap dah bener fer, lanjut ke challenge nya ya

2021-08-06 08:42 UTC, merged